In [3]:
import numpy as np

In [97]:
# 2
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [84]:
# 3
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [87]:
# 4
a[a % 2] # % calculates the remainder of division between two numbers.

a[a  % 2 == 0] # index out all even numbers

a[a % 2 != 0] # index all odd numbers

array([1, 3, 5, 7, 9])

In [88]:
# 5
a[a % 2 != 0] = -1
a


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [133]:
# 6
a = np.arange(10)

a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [118]:
# 7
a = np.arange(10)

np.mean(a)

np.median(a)

np.std(a)

2.8722813232690143

In [148]:
# 8
b = np.random.rand(5,5)
mean = b.mean() # or np.mean(b)
std = b.std()

(b - mean)/std

array([[-1.17737534,  1.0976847 , -0.47523659,  0.28714882,  0.56561187],
       [ 0.82098686,  1.85755564, -1.28417702,  1.83453945, -1.07957141],
       [-0.95955   , -0.20198907,  0.30924561,  0.39507648,  1.91297427],
       [-0.4225496 , -0.36929907, -1.3829872 ,  0.69074939, -0.54611416],
       [ 1.11013236, -0.46508871, -0.75162171, -0.99936319, -0.76678237]])

In [165]:
# 9
a = np.random.randint(0,25,(5,3), dtype= int)
b = np.random.randint(0,25,(3,5), dtype= int)

np.dot(a,b)

array([[726, 382, 610, 165, 516],
       [132, 285, 304, 159, 253],
       [286, 179, 388, 208, 393],
       [902, 526, 906, 341, 820],
       [638, 705, 895, 395, 765]])

In [211]:
# 10
arr = np.array([1,2,3,4,5,6,7,8,9,9,9,8,7,6,5,6,5,6,5,4,3,2,1,2,3,4,29])
print(arr)
np.unique(arr, return_counts=True) # prints unique members and counts of each unique number




[ 1  2  3  4  5  6  7  8  9  9  9  8  7  6  5  6  5  6  5  4  3  2  1  2
  3  4 29]


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 29]),
 array([2, 3, 3, 3, 4, 4, 2, 2, 3, 1], dtype=int64))